# Generated by Django 3.2.10 on 2023-04-11 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drives',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drive_name', models.CharField(default='', max_length=255)),
                ('drive_desc', models.TextField(default='')),
                ('drive_pckg', models.CharField(default='', max_length=255)),
                ('drive_date', models.CharField(default='', max_length=255)),
                ('drive_bklgs', models.CharField(default='', max_length=255)),
                ('drive_cgpa', models.CharField(default='', max_length=255)),
                ('drive_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('drive_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('ph_num', models.TextField(max_length=10)),
                ('addr', models.TextField()),
                ('clg_name', models.CharField(max_length=50)),
                ('sem', models.CharField(max_length=10)),
                ('brch', models.TextField()),
                ('cgpa', models.TextField()),
                ('bklgs', models.TextField()),
                ('website', models.TextField()),
                ('github', models.TextField()),
                ('linkedin', models.TextField()),
                ('stkoflw', models.TextField()),
                ('codechef', models.TextField()),
                ('dp_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('isCordinator', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Registered',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razor_pay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razor_pay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razor_pay_payment_signature', models.CharField(blank=True, max_length=100, null=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.drives')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
