# Generated by Django 3.2.10 on 2023-04-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20230412_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='drives',
            name='drive_role',
            field=models.CharField(default='', max_length=255),
        ),
    ]
