# Generated by Django 4.0.5 on 2023-04-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_drives_drive_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drives',
            name='drive_bklgs',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='drives',
            name='drive_cgpa',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='drives',
            name='drive_date',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='drives',
            name='drive_desc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='drives',
            name='drive_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='drives',
            name='drive_pckg',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='drives',
            name='drive_role',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
