# Generated by Django 4.0.5 on 2023-04-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_drives_drive_bklgs_alter_drives_drive_cgpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
