# Generated by Django 3.2.10 on 2023-04-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='isCordinator',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
