# Generated by Django 4.0.5 on 2023-04-26 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0008_auto_20230424_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registered',
            name='razor_pay_order_id',
        ),
        migrations.RemoveField(
            model_name='registered',
            name='razor_pay_payment_id',
        ),
        migrations.RemoveField(
            model_name='registered',
            name='razor_pay_payment_signature',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
