# Generated by Django 4.0.5 on 2023-04-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_profile_bklgs_alter_profile_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bklgs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='cgpa',
            field=models.FloatField(),
        ),
    ]
