# Generated by Django 4.0.5 on 2023-05-21 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_drives_drive_cdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drives',
            old_name='id',
            new_name='drive_id',
        ),
    ]
