# Generated by Django 4.0.5 on 2023-05-21 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_rename_id_drives_drive_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drives',
            old_name='drive_id',
            new_name='id',
        ),
    ]
